language: node_js
node_js:
- '7'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: a0w5E7C5SVML9HeQ1r8OjPvAukbrMNWq5lRsI10eHlEgt0zxQgX3ToOqr2ldu9qJQtjZ/iEwyr+3aeVB/xziggYWXZ+6MUeVJiCRVyeeeTKweYBnwXp96/CzfihBX68QYUE4b7x8Ip8TKrCuRVOMFGFL0tZWYcpNgbKLDh2IUZel3GVnsPOcl8KRtLYp9es6tTDdnWpElwbNZClSdkns8On81poSC7m7SwCgzYwevlmanfidYOUxHnzJyoBOpCONJdgnD7UfMEElI/av2YF6TmpvJ4Mycrhz0OHJLfzO8Ee1/iiv/w15KS6TlDmJWG5ddnLa0DE+XNq97UAE9lgSpHnKp1//8rM6hjSNJY3FiBLdmah6xa8+xIkcwJsxxkTeYU1rOxhWMdavqG/YPA4qj8JDhs//1tf4T6Y0ClHpjNMk9KphAhkXTqDm24ZohOJtIS7oXnm3qPMfOc9LFPwuwW69UwHN8reWO94hLNGoit/l5bvx96yb896fmCb3ln0iU163K94+hk+GL8H4neFDgcLucTlqJ+C9T5IjV5dju7UCU10RWaKnSP0raEB8VpuIGtuwog9SAqmSVrE+aZQHrOMnu8HjITW1OZ/VmPqfMz45BlsiMfeD35rJI9o4cR7frFVH2A/6wweouSl++pWFBAy/td3bPhH7jDpRL5CjiI8=
deploy:
  provider: npm
  email: deptno@gmail.com
  skip_cleanup: true
  api_key:
    secure: vzd5Ur7AnH/FpzctukyZzrDfNsEUmcd1QrvQ1eFF83JvHT+d5w+9CdrDwbQ6aXcZJ09OZGFWnSiVMdaSaZeIHxc4qzn6jVEkve/MObzFcCqIwo6hFrzpMGdkehE+hYuNihflXWTJ4Xg/QFrsumyceQMDK0b4RtKrC7fYPbbsr86gfNgS52W2U+YR0i2NNOSCWfly8X1u0rrKw0OcWq4Xl9BBofJ/i9fhsUPT65gpc/GVAh8o9FaFy9tMZj99m07yGOV8F9OUh32GFP8LRY6bEAz0jEO26BI/zPq2zrsy34Ut+iRAE8tEwEBoBfS73YVoBWtITGuBvpcSdgLIm8XwitcBWNQYU+nmgu0ot9AZPzi50/pM2xozo2CMFpEqkvOiH+D/I0oCl2aV0lGtQn1EZAryiwriHR2Pf298NCdQi89qyX3zzhRjBRR3lWDLpLJVtSPa9jmu77IS3dF0bOfdQILJNi9xF37TDWbRzu1rLVKI+tBCNyuj/feUoMXHr0GNLxjoGme9FPu63AXf/OllOdCJvRap4TkBZP/Jf1vD70mYEas/kDDgrIhj3QxI/oA6MwC6LOzsSzOqGFn6xHeprwFhWkr4uNZ9AIF9zFZO+BqRrsjoUhKFhRSX9GZqAe3PsQ7IRXUe9nBbPfU1J74cJi8bqkJfO05lgGQzjtE+o7Q=
